apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playzone-images-pvc
  namespace: play-zone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: playzone-images-pv
