apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
  namespace: play-zone
spec:
  serviceName: "sql-server"
  replicas: 1

  selector:
    matchLabels:
      app: sql-server

  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "PlayZone@123"
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: sql-storage
              mountPath: /var/opt/mssql

          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: sql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: play-zone
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
